name: PyTest

on:
  push:
    branches: [first-actions]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint main.py ./app --disable=C,R
          pylint conftest.py ./tests --disable=C,R
      - name: Test with pytest
        run: |
          pytest
      - name: Coverage test with pytest
        run: |
          coverage run -m pytest
          coverage report
